/**
 * WANDR - Merchants of the Realm Database
 * Curated independent merchants, artisans, and covens across the active ward grid.
 */
const INITIAL_MERCHANTS = [
  {
    id: 'moonlight-bakery',
    name: 'Moonlight Bakery',
    coven: "Bakers' Coven",
    covenIcon: '🍞',
    rarity: 'Rare',
    rarityColor: '#38BDF8',
    coords: [37.7758, -122.4215],
    address: '422 San Carlos St, Hayes Ward',
    distanceKm: 0.8,
    distanceText: '0.8 KM AWAY',
    hours: 'Open till 4 PM',
    isOpen: true,
    xp: 75,
    rating: 4.9,
    reviews: 128,
    lore: 'Fresh sourdough baked before sunrise under crescent moons. Ancient stone milling meets naturally leavened doughs and seasonal cardamoms baked in a hearth built in 1912.',
    secretPerk: 'Whisper "Crescent Hearth" at checkout for a complimentary cardamom knot.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZj5dApRgTMYHnOTLT0q08qdINYcrClX70Lwz5rr1tN5JfdSC6hHTq9gMRouK1LtPe6nIht2aornbAQ9Qcommue2nYftyxMcP9SbFgHpRh5Qpgy5X9Adc68xVhsndL3qA3XGyyhpQf7_WErOJHD_lkiqzR0puBQ2pSh3JEZ7efi6NgfCRSCDE5Gu1AJZbtBLPnvTYvk_fLQW6HYph7kYgYAGc_a3MZhBAM7kOmqIy-mn_QTk1BqFg14A',
    isMystery: false,
    keeperName: 'Baker-Alchemist Soren'
  },
  {
    id: 'alchemist-apothecary',
    name: 'Alchemist Apothecary',
    coven: 'Potions & Elixirs',
    covenIcon: '🧪',
    rarity: 'Epic',
    rarityColor: '#B347FF',
    coords: [37.7732, -122.4228],
    address: '185 Valencia Pass, Sector-09',
    distanceKm: 1.2,
    distanceText: '1.2 KM AWAY',
    hours: 'Open till 7 PM',
    isOpen: true,
    xp: 120,
    rating: 5.0,
    reviews: 94,
    lore: 'Handcrafted herbal elixirs, botanical tinctures, and small-batch skincare distilled from wildcrafted coastal flora and night-blooming botanicals.',
    secretPerk: 'Show your WANDR app to receive a vial of calming blue lotus mist with any tea purchase.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBwD_xegWwLkeCkuCJ3JC0-klZbjfkYYl_5uFGpRrOPjUBMkLIxA0lZEwMlOjrNBgUHRKRz5lUd3g-CTEUfnQLgjSkjccx4fSpBRl_NdJYR29Bso7cAHY2BC2Yfx3QzCy1FTa028fc-uvmwinyyxWU8xvgRIjFNrnFO_L5zwVffNsPsvOPPVGkKr0g4XzPC-nKVkSdHMZssqJn9-vcgmzhbGCFQsh2y9ji4smKqXqFWN0LsuZ0PHPqrHg',
    isMystery: false,
    keeperName: 'Herbalist Marigold'
  },
  {
    id: 'the-neon-loom',
    name: 'The Neon Loom',
    coven: 'Enchanted Threads',
    covenIcon: '🧵',
    rarity: 'Uncommon',
    rarityColor: '#00F59B',
    coords: [37.7765, -122.4172],
    address: '89 Hayes Blvd, Atelier 4',
    distanceKm: 0.4,
    distanceText: '0.4 KM AWAY',
    hours: 'Closes in 45m (7:30 PM)',
    isOpen: true,
    xp: 50,
    rating: 4.8,
    reviews: 205,
    lore: 'Custom streetwear, deadstock Japanese textile restorations, and embroidered arcane sigils hand-stitched by master tailor Jaxen on antique mechanical looms.',
    secretPerk: 'Free luminescent ward patch sewn onto any jacket brought into the workshop.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiRPMQ1asfZ51y2UUsxgZJ_t5ayXWgNyvO9q1lY-mb2llgK5tVRsYfPcheF8GXtdSe0dXA1vBgSA0xtcq3nAUtZGXhoF_oXXrNuf4IDLZJip8yJKdMMEHJlx8-mie1kqoOxRsme_h_g5BY5VKGFSAL5F_QsNrmDhIhkg7owEMUu0nB2qZydJJPxZlfh_BExVQQ0562LvqYNY7XI9UmsNVDIZGGFOe8YRZyLPkUzQ-gak4ZRGFvqNajTg',
    isMystery: false,
    keeperName: 'Tailor Jaxen'
  },
  {
    id: 'the-obsidian-tome',
    name: 'The Obsidian Tome',
    coven: 'Arcane Goods',
    covenIcon: '🔮',
    rarity: 'Epic',
    rarityColor: '#B347FF',
    coords: [37.7741, -122.4182],
    address: 'Secret Alleyway off Octavia St',
    distanceKm: 0.32,
    distanceText: '320M AWAY',
    hours: 'Open till 11 PM',
    isOpen: true,
    xp: 150,
    rating: 4.95,
    reviews: 77,
    lore: 'A hidden bookstore and oddities sanctum concealed behind an unpretentious espresso hatch. Rare first editions, tarot codices, and obsidian scrying crystals.',
    secretPerk: 'Say "I seek the Fourth Sphere" to the barista for access to the hidden rear library.',
    image: 'https://images.unsplash.com/photo-1507842229451-79b1be8d6293?auto=format&fit=crop&w=800&q=80',
    isMystery: true,
    keeperName: 'Archivist Thorne'
  },
  {
    id: 'mandrake-elixirs',
    name: 'Mandrake Elixirs & Teas',
    coven: 'Potions & Elixirs',
    covenIcon: '🧪',
    rarity: 'Uncommon',
    rarityColor: '#00F59B',
    coords: [37.7772, -122.4208],
    address: '312 Grove Street, Ward Gate',
    distanceKm: 0.18,
    distanceText: '180M AWAY',
    hours: 'Open till 8 PM',
    isOpen: true,
    xp: 50,
    rating: 4.75,
    reviews: 142,
    lore: 'Herbal tonics brewed over bubbling copper cauldrons with organic reishi, lion’s mane, and hand-foraged yerba herbs from northern misty ridges.',
    secretPerk: '20% off your second infusion refill with an active Wandr daily streak.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
    isMystery: false,
    keeperName: 'Apothecary Lyra'
  },
  {
    id: 'solstice-vinyl',
    name: 'Solstice Vinyl & Curios',
    coven: 'Arcane Relics',
    covenIcon: '🎵',
    rarity: 'Rare',
    rarityColor: '#38BDF8',
    coords: [37.7725, -122.4168],
    address: '584 Mission Pass, Vault 2',
    distanceKm: 0.65,
    distanceText: '650M AWAY',
    hours: 'Open till 9 PM',
    isOpen: true,
    xp: 85,
    rating: 4.88,
    reviews: 180,
    lore: 'Analog vinyl rarities from 1968 to present, vintage synthesizers, and vacuum tube amplifiers restored with meticulous mechanical reverence.',
    secretPerk: 'Private 15-minute listening booth session with any purchase above $15.',
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
    isMystery: false,
    keeperName: 'Curator Milo'
  },
  {
    id: 'celestial-roasters',
    name: 'Celestial Roasters',
    coven: 'Coffee Alchemy',
    covenIcon: '☕',
    rarity: 'Uncommon',
    rarityColor: '#00F59B',
    coords: [37.7752, -122.4241],
    address: '144 Fell Street',
    distanceKm: 0.5,
    distanceText: '500M AWAY',
    hours: 'Open till 5 PM',
    isOpen: true,
    xp: 40,
    rating: 4.92,
    reviews: 310,
    lore: 'Single-origin Ethiopian and anaerobic fermented coffees roasted in micro-batches with precision thermal profiling and volcanic mineralized water.',
    secretPerk: 'Free pour-over tasting flight upgrade on first explorer check-in.',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80',
    isMystery: false,
    keeperName: 'Roaster Elena'
  },
  {
    id: 'astral-ceramics',
    name: 'Astral Earth Ceramics',
    coven: 'Arcane Goods',
    covenIcon: '🏺',
    rarity: 'Legendary',
    rarityColor: '#FFD15C',
    coords: [37.7718, -122.4199],
    address: '920 Folsom Sanctum',
    distanceKm: 0.95,
    distanceText: '950M AWAY',
    hours: 'Open till 6 PM',
    isOpen: true,
    xp: 200,
    rating: 5.0,
    reviews: 62,
    lore: 'Wood-fired stoneware and crystalline glaze pottery hand-thrown using wild clays harvested from dormant volcanic caldera basins.',
    secretPerk: 'Collect an exclusive ceramic explorer talisman upon completing a 7-day streak.',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    isMystery: false,
    keeperName: 'Master Potter Kael'
  }
];

window.WANDR_MERCHANTS = INITIAL_MERCHANTS;
