/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#2f004d",
        "secondary-container": "#8900d5",
        "on-tertiary-fixed-variant": "#5a4400",
        "error-container": "#93000a",
        "tertiary-container": "#ffd15c",
        "inverse-primary": "#006d42",
        "hud-glow-violet": "rgba(179, 71, 255, 0.25)",
        "on-surface": "#e2e2eb",
        "on-tertiary-container": "#755900",
        "text-secondary": "#94A3B8",
        "on-primary-fixed": "#002111",
        "on-secondary-fixed-variant": "#6e00ab",
        "on-error": "#690005",
        "secondary-fixed": "#f3daff",
        "amber-ember": "#E6B032",
        "tertiary": "#fff2da",
        "outline": "#849588",
        "surface-container-high": "#282a31",
        "on-background": "#e2e2eb",
        "inverse-on-surface": "#2e3037",
        "background": "#111319",
        "on-error-container": "#ffdad6",
        "text-muted": "#64748B",
        "on-tertiary": "#3e2e00",
        "primary-fixed": "#53ffab",
        "electric-violet": "#B347FF",
        "surface-container-lowest": "#0c0e14",
        "rarity-rare": "#38BDF8",
        "surface-container-highest": "#33343c",
        "neon-mint": "#00F59B",
        "surface-container-low": "#191b22",
        "on-tertiary-fixed": "#251a00",
        "rarity-common": "#8E9BB0",
        "on-primary-container": "#006b41",
        "surface-card-hover": "#171F32",
        "neon-lime": "#39FF14",
        "surface-dim": "#111319",
        "error": "#ffb4ab",
        "surface-variant": "#33343c",
        "magical-gold": "#FFD15C",
        "text-primary": "#F1F5F9",
        "surface-card": "#0F1420",
        "midnight-green": "#0B1617",
        "secondary-fixed-dim": "#e2b6ff",
        "rarity-uncommon": "#00F59B",
        "hud-glow-gold": "rgba(255, 209, 92, 0.28)",
        "tertiary-fixed": "#ffdf97",
        "on-surface-variant": "#b9cbbd",
        "on-secondary-container": "#e9c3ff",
        "primary-container": "#00f59b",
        "rarity-legendary": "#FFD15C",
        "primary-fixed-dim": "#00e38f",
        "rarity-epic": "#B347FF",
        "on-secondary": "#4d007a",
        "on-primary": "#003920",
        "secondary": "#e2b6ff",
        "surface": "#111319",
        "obsidian-deep": "#080A10",
        "surface-container": "#1d1f26",
        "inverse-surface": "#e2e2eb",
        "on-primary-fixed-variant": "#005231",
        "primary": "#cdffdc",
        "arcane-violet-surface": "#130E24",
        "hud-glow-green": "rgba(0, 245, 155, 0.25)",
        "tertiary-fixed-dim": "#edc14e",
        "outline-variant": "#3b4a3f",
        "surface-tint": "#00e38f",
        "surface-bright": "#373940"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xxs": "0.125rem",
        "ward-max-width": "1280px",
        "grid-gutter-desktop": "1.5rem",
        "space-2xl": "3rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "hud-inset": "1rem",
        "space-4xl": "6rem",
        "space-lg": "1.5rem",
        "space-3xl": "4rem",
        "space-base": "1rem",
        "grid-gutter-mobile": "0.75rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "code-pill": ["Space Mono", "monospace"],
        "badge-arcade": ["Space Mono", "monospace"],
        "hud-stat": ["Space Mono", "monospace"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "display-hero-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["13px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "display-hero": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600"}],
        "code-pill": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "badge-arcade": ["11px", {"lineHeight": "14px", "letterSpacing": "0.12em", "fontWeight": "700"}],
        "hud-stat": ["14px", {"lineHeight": "18px", "letterSpacing": "0.08em", "fontWeight": "700"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "-0.005em", "fontWeight": "400"}],
        "body-md": ["15px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-hero-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-xl-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
